ii
after_success: 
  - ./apk.sh
dist: precise
android: 
  components: 
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - android-23
    - add-on
    - extra
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
licenses:
  - android-sdk-preview-license-c81a61d9
  - android-sdk-license-.+
  - google-gdk-license-.+

before_cache: 
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"
before_install: 
  - "export JAVA7_HOME=/usr/lib/jvm/java-7-oracle"
  - "export JAVA8_HOME=/usr/lib/jvm/java-8-oracle"
  - "export JAVA_HOME=$JAVA8_HOME"
#  - "git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root"
#  - "export ANDROID_NDK_HOME=$HOME/android-ndk-root"
#  - "echo \"ndk.dir=$ANDROID_NDK_HOME\" > local.properties"
cache: 
  directories: 
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy: 
  api_key: $GITHUB_TOKEN
  file: app/build/outputs/apk/app-release.apk
  provider: releases
  skip_cleanup: true
  true: 
    repo: isjang98/embossingAnimation
    tags: true
env: 
  global: 
    - NDK_VERSION=r11c
language: android
notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients: 
      - isjang98@gmail.com
  on_failure: always
  on_success: always
  slack: "droidknight2018:LGIZ5vEnnHyAPbACXVXLGIB4"
script:
  - echo "apiKey=$API_KEY" >> ./app/fabric.properties
  - echo "apiSecret=$API_SECRET" >> ./app/fabric.properties
  - ./gradlew build
after_script:
  - ./gradlew assembleRelease crashlyticsUploadDistributionRelease
sudo: required

